name: knuckles

options:
  bundleIdPrefix: com.kylebashour
  deploymentTarget: 
    iOS: "13.1"

configFiles:
  Debug: xcconfig/Project-Debug.xcconfig
  Release: xcconfig/Project-Release.xcconfig

targets:

  Knuckles:
    type: application
    platform: iOS

    configFiles:
      Debug: xcconfig/Knuckles-Debug.xcconfig
      Release: xcconfig/Knuckles-Release.xcconfig
    
    preBuildScripts:
      - path: tools/swiftlint.sh
        name: Run swiftlint
    
    scheme:
      testTargets: [KnucklesTests]
    
    sources:
      - path: Sources/Knuckles
      - path: Sources/Core
    
    dependencies:
      - target: TodayExtension
      - carthage: LinkKit
    
    entitlements:
      path: knuckles.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    
    settings:
      INFOPLIST_FILE: Sources/Knuckles/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: "com.kylebashour.knuckles"
      VERSIONING_SYSTEM: Apple Generic
      CURRENT_PROJECT_VERSION: 1
      TARGETED_DEVICE_FAMILY: 1
  
  KnucklesTests:
    type: bundle.unit-test
    platform: iOS
  
    sources:
      - path: Tests
  
    dependencies:
      - target: Knuckles

  TodayExtension:
    type: app-extension
    platform: iOS

    dependencies:
      - sdk: NotificationCenter.framework

    configFiles:
      Debug: xcconfig/TodayExtension-Debug.xcconfig
      Release: xcconfig/TodayExtension-Release.xcconfig

    sources:
      - path: Sources/TodayExtension
      - path: Sources/Core

    settings:
      INFOPLIST_FILE: Sources/TodayExtension/Info.plist
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
      PRODUCT_BUNDLE_IDENTIFIER: "com.kylebashour.knuckles.TodayExtension"

