name: knuckles

options:
  bundleIdPrefix: com.kylebashour
  deploymentTarget: 
    iOS: "13.1"

configFiles:
  Debug: xcconfig/Project-Debug.xcconfig
  Release: xcconfig/Project-Release.xcconfig

targets:

  Knuckles:
    type: application
    platform: iOS

    configFiles:
      Debug: xcconfig/Knuckles-Debug.xcconfig
      Release: xcconfig/Knuckles-Release.xcconfig
    
    preBuildScripts:
      - path: tools/swiftlint.sh
        name: Run swiftlint
    postBuildScripts:
      - path: tools/prepare-plaid.sh
        name: Prepare Plaid for Distribution
    
    scheme:
      testTargets: [KnucklesTests]
    
    sources:
      - path: Sources/Knuckles
      - path: Sources/Core
      - path: Sources/Widget/Assets/Widget.intentdefinition
    
    dependencies:
      - target: Widget
    
    entitlements:
      path: knuckles.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.security.application-groups:
          - group.com.kylebashour.knuckles
    
    settings:
      INFOPLIST_FILE: Sources/Knuckles/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: "com.kylebashour.knuckles"
      VERSIONING_SYSTEM: Apple Generic
      CURRENT_PROJECT_VERSION: 1
      TARGETED_DEVICE_FAMILY: 1
      MARKETING_VERSION: "0.0.1"
  
  KnucklesTests:
    type: bundle.unit-test
    platform: iOS
  
    sources:
      - path: Tests
  
    dependencies:
      - target: Knuckles

  Widget:
    type: app-extension
    platform: iOS

    dependencies:
      - sdk: WidgetKit.framework

    entitlements:
      path: Widget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.kylebashour.knuckles

    configFiles:
      Debug: xcconfig/TodayExtension-Debug.xcconfig
      Release: xcconfig/TodayExtension-Release.xcconfig

    sources:
      - path: Sources/Widget
      - path: Sources/Core

    settings:
      MARKETING_VERSION: "0.0.1"
      CURRENT_PROJECT_VERSION: 1
      IPHONEOS_DEPLOYMENT_TARGET: 14.0
      INFOPLIST_FILE: Sources/Widget/Info.plist
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
      PRODUCT_BUNDLE_IDENTIFIER: "com.kylebashour.knuckles.Widget"

