name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rake
      run: rake
    - name: Run tests
      run: xcodebuild test -scheme Knuckles -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4.1'
